export const SET_SPLASH = 'SET_SPLASH';
export const SET_USER = 'SET_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_USER_ONBOARDING_SCREEN = 'SET_USER_ONBOARDING_SCREEN';

export const SHOW_USER_ONBOARDING_SCREEN = 'SHOW_USER_ONBOARDING_SCREEN';

export const SET_ERROR = 'SET_ERROR';
export const SET_SUCCESS = 'SET_SUCCESS';

export const RESET_STORE = 'RESET_STORE';

export const RESET_ONLY_ALERT_FROM_STORE = 'RESET_ONLY_ALERT_FROM_STORE';

export const SET_NET_INFO = 'SET_NET_INFO';

export const HEADER_TITLE = 'HEADER_TITLE';

export const RESET_ONLY_HIRE_BUY_STORE = 'RESET_ONLY_HIRE_BUY_STORE';

export const PRESENT_LOADER = 'PRESENT_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

export const PRESENT_MODAL_LOADER = 'PRESENT_MODAL_LOADER';
export const HIDE_MODAL_LOADER = 'HIDE_MODAL_LOADER';

export const PRESENT_ALERT = 'PRESENT_ALERT';
export const HIDE_ALERT = 'HIDE_ALERT';

export const RESET_NAVIGATION_ROUTES = 'RESET_NAVIGATION_ROUTES';

export const FOCUSED_SCREEN = 'FOCUSED_SCREEN';
export const MATERIAL_TOP_TAB_FOCUSED_SCREEN =
	'MATERIAL_TOP_TAB_FOCUSED_SCREEN';

export const CLEAR_TEXT_INPUT = 'CLEAR_TEXT_INPUT';

export const ANIMATION_VALIDATE = 'ANIMATION_VALIDATE';
export const BACK_BUTTON_ANIMATION = 'BACK_BUTTON_ANIMATION';

export const PRESENT_ADVERT_SCREEN_MODAL = 'PRESENT_ADVERT_SCREEN_MODAL';
export const HIDE_ADVERT_SCREEN_MODAL = 'HIDE_ADVERT_SCREEN_MODAL';

export const LOGIN_POST_API_REQUEST = 'LOGIN_POST_API_REQUEST';
export const LOGIN_POST_API_SUCCESS = 'LOGIN_POST_API_SUCCESS';
export const LOGIN_POST_API_FAILURE = 'LOGIN_POST_API_FAILURE';

export const PRESENT_SOCIAL_MEDIA_TERMS_POLICIES =
	'PRESENT_SOCIAL_MEDIA_TERMS_POLICIES';
export const HIDE_SOCIAL_MEDIA_TERMS_POLICIES =
	'HIDE_SOCIAL_MEDIA_TERMS_POLICIES';

export const REGISTER_POST_API_REQUEST = 'REGISTER_POST_API_REQUEST';
export const REGISTER_POST_API_SUCCESS = 'REGISTER_POST_API_SUCCESS';
export const REGISTER_POST_API_FAILURE = 'REGISTER_POST_API_FAILURE';

export const PRESENT_USER_DETAIL_SCREEN_MODAL =
	'PRESENT_USER_DETAIL_SCREEN_MODAL';
export const HIDE_USER_DETAIL_SCREEN_MODAL = 'HIDE_USER_DETAIL_SCREEN_MODAL';

export const USER_DETAIL_GET_API_REQUEST = 'USER_DETAIL_GET_API_REQUEST';
export const USER_DETAIL_GET_API_SUCCESS = 'USER_DETAIL_GET_API_SUCCESS';
export const USER_DETAIL_GET_API_FAILURE = 'USER_DETAIL_GET_API_FAILURE';

export const USER_ONBOARDING_ADDRESS_POST_API_REQUEST =
	'USER_ONBOARDING_ADDRESS_POST_API_REQUEST';
export const USER_ONBOARDING_ADDRESS_POST_API_SUCCESS =
	'USER_ONBOARDING_ADDRESS_POST_API_SUCCESS';
export const USER_ONBOARDING_ADDRESS_POST_API_FAILURE =
	'USER_ONBOARDING_ADDRESS_POST_API_FAILURE';

export const USER_DETAIL_PUT_API_REQUEST = 'USER_DETAIL_PUT_API_REQUEST';
export const USER_DETAIL_PUT_API_SUCCESS = 'USER_DETAIL_PUT_API_SUCCESS';
export const USER_DETAIL_PUT_API_FAILURE = 'USER_DETAIL_PUT_API_FAILURE';

export const CLEAR_SEARCH_LANDING_PICKER_VALUE =
	'CLEAR_SEARCH_LANDING_PICKER_VALUE';

export const SEARCH_ITEM_HIRE_POST_API_REQUEST =
	'SEARCH_ITEM_HIRE_POST_API_REQUEST';
export const SEARCH_ITEM_HIRE_POST_API_SUCCESS =
	'SEARCH_ITEM_HIRE_POST_API_SUCCESS';
export const SEARCH_ITEM_HIRE_POST_API_FAILURE =
	'SEARCH_ITEM_HIRE_POST_API_FAILURE';

export const SEARCH_ITEM_BUY_POST_API_REQUEST =
	'SEARCH_ITEM_BUY_POST_API_REQUEST';
export const SEARCH_ITEM_BUY_POST_API_SUCCESS =
	'SEARCH_ITEM_BUY_POST_API_SUCCESS';
export const SEARCH_ITEM_BUY_POST_API_FAILURE =
	'SEARCH_ITEM_BUY_POST_API_FAILURE';

export const CATEGORIES_GET_API_REQUEST = 'CATEGORIES_GET_API_REQUEST';
export const CATEGORIES_GET_API_SUCCESS = 'CATEGORIES_GET_API_SUCCESS';
export const CATEGORIES_GET_API_FAILURE = 'CATEGORIES_GET_API_FAILURE';

export const SUB_CATEGORIES_GET_API_REQUEST = 'SUB_CATEGORIES_GET_API_REQUEST';
export const SUB_CATEGORIES_GET_API_SUCCESS = 'SUB_CATEGORIES_GET_API_SUCCESS';
export const SUB_CATEGORIES_GET_API_FAILURE = 'SUB_CATEGORIES_GET_API_FAILURE';

export const PRESENT_FILTER_HIRE_SEARCH_ITEM_SCREEN_MODAL =
	'PRESENT_FILTER_HIRE_SEARCH_ITEM_SCREEN_MODAL';
export const HIDE_FILTER_HIRE_SEARCH_ITEM_SCREEN_MODAL =
	'HIDE_FILTER_HIRE_SEARCH_ITEM_SCREEN_MODAL';

export const PRESENT_FILTER_BUY_SEARCH_ITEM_SCREEN_MODAL =
	'PRESENT_FILTER_BUY_SEARCH_ITEM_SCREEN_MODAL';
export const HIDE_FILTER_BUY_SEARCH_ITEM_SCREEN_MODAL =
	'HIDE_FILTER_BUY_SEARCH_ITEM_SCREEN_MODAL';

export const PRESENT_SEARCH_ITEM_SORT_SCREEN_MODAL =
	'PRESENT_SEARCH_ITEM_SORT_SCREEN_MODAL';
export const HIDE_SEARCH_ITEM_SORT_SCREEN_MODAL =
	'HIDE_SEARCH_ITEM_SORT_SCREEN_MODAL';

export const FILTER_SEARCH_ITEM_POST_API_REQUEST =
	'FILTER_SEARCH_ITEM_POST_API_REQUEST';
export const FILTER_SEARCH_ITEM_POST_API_SUCCESS =
	'FILTER_SEARCH_ITEM_POST_API_SUCCESS';
export const FILTER_SEARCH_ITEM_POST_API_FAILURE =
	'FILTER_SEARCH_ITEM_POST_API_FAILURE';

export const FILTER_SEARCH_ITEM_BUY_POST_API_REQUEST =
	'FILTER_SEARCH_ITEM_BUY_POST_API_REQUEST';
export const FILTER_SEARCH_ITEM_BUY_POST_API_SUCCESS =
	'FILTER_SEARCH_ITEM_BUY_POST_API_SUCCESS';
export const FILTER_SEARCH_ITEM_BUY_POST_API_FAILURE =
	'FILTER_SEARCH_ITEM_BUY_POST_API_FAILURE';

export const RESET_FILTER_SEARCH_DATA = 'RESET_FILTER_SEARCH_DATA';

export const PRESENT_PHOTOS_SCREEN_MODAL = 'PRESENT_PHOTOS_SCREEN_MODAL';
export const HIDE_PHOTOS_SCREEN_MODAL = 'HIDE_PHOTOS_SCREEN_MODAL';

export const REMOVE_ADVERT_ERROR_MESSAGE = 'REMOVE_ADVERT_ERROR_MESSAGE';

export const CREATE_ADVERT_POST_API_REQUEST = 'CREATE_ADVERT_POST_API_REQUEST';
export const CREATE_ADVERT_POST_API_SUCCESS = 'CREATE_ADVERT_POST_API_SUCCESS';
export const CREATE_ADVERT_POST_API_FAILURE = 'CREATE_ADVERT_POST_API_FAILURE';

export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';

export const STORE_PHOTOS_POST_API_REQUEST = 'STORE_PHOTOS_POST_API_REQUEST';
export const STORE_PHOTOS_POST_API_SUCCESS = 'STORE_PHOTOS_POST_API_SUCCESS';
export const STORE_PHOTOS_POST_API_FAILURE = 'STORE_PHOTOS_POST_API_FAILURE';

export const PHOTO_DELETE_API_REQUEST = 'PHOTO_DELETE_API_REQUEST';
export const PHOTO_DELETE_API_SUCCESS = 'PHOTO_DELETE_API_SUCCESS';
export const PHOTO_DELETE_API_FAILURE = 'PHOTO_DELETE_API_FAILURE';

export const UPDATE_ADVERT_POST_API_REQUEST = 'UPDATE_ADVERT_POST_API_REQUEST';
export const UPDATE_ADVERT_POST_API_SUCCESS = 'UPDATE_ADVERT_POST_API_SUCCESS';
export const UPDATE_ADVERT_POST_API_FAILURE = 'UPDATE_ADVERT_POST_API_FAILURE';

export const ADVERT_LIST_GET_API_REQUEST = 'ADVERT_LIST_GET_API_REQUEST';
export const ADVERT_LIST_GET_API_SUCCESS = 'ADVERT_LIST_GET_API_SUCCESS';
export const ADVERT_LIST_GET_API_FAILURE = 'ADVERT_LIST_GET_API_FAILURE';

export const ADVERT_BY_ID_GET_API_REQUEST = 'ADVERT_BY_ID_GET_API_REQUEST';
export const ADVERT_BY_ID_GET_API_SUCCESS = 'ADVERT_BY_ID_GET_API_SUCCESS';
export const ADVERT_BY_ID_GET_API_FAILURE = 'ADVERT_BY_ID_GET_API_FAILURE';

export const ADVERT_DELETE_SUCCESS = 'ADVERT_DELETE_SUCCESS';
export const ADVERT_DELETING_OBJECT = 'ADVERT_DELETING_OBJECT';

export const ADVERT_BY_ID_DELETE_API_REQUEST =
	'ADVERT_BY_ID_DELETE_API_REQUEST';
export const ADVERT_BY_ID_DELETE_API_SUCCESS =
	'ADVERT_BY_ID_DELETE_API_SUCCESS';
export const ADVERT_BY_ID_DELETE_API_FAILURE =
	'ADVERT_BY_ID_DELETE_API_FAILURE';

export const PRESENT_ADDRESS_SCREEN_MODAL = 'PRESENT_ADDRESS_SCREEN_MODAL';
export const HIDE_ADDRESS_SCREEN_MODAL = 'HIDE_ADDRESS_SCREEN_MODAL';

export const ADDRESS_ADD_SUCCESS = 'ADDRESS_ADD_SUCCESS';

export const CREATE_ADDRESS_POST_API_REQUEST =
	'CREATE_ADDRESS_POST_API_REQUEST';
export const CREATE_ADDRESS_POST_API_SUCCESS =
	'CREATE_ADDRESS_POST_API_SUCCESS';
export const CREATE_ADDRESS_POST_API_FAILURE =
	'CREATE_ADDRESS_POST_API_FAILURE';

export const ADDRESS_BY_ID_GET_API_REQUEST = 'ADDRESS_BY_ID_GET_API_REQUEST';
export const ADDRESS_BY_ID_GET_API_SUCCESS = 'ADDRESS_BY_ID_GET_API_SUCCESS';
export const ADDRESS_BY_ID_GET_API_FAILURE = 'ADDRESS_BY_ID_GET_API_FAILURE';

export const ADDRESS_PUT_API_REQUEST = 'ADDRESS_PUT_API_REQUEST';
export const ADDRESS_PUT_API_SUCCESS = 'ADDRESS_PUT_API_SUCCESS';
export const ADDRESS_PUT_API_FAILURE = 'ADDRESS_PUT_API_FAILURE';

export const ADDRESS_LIST_GET_API_REQUEST = 'ADDRESS_LIST_GET_API_REQUEST';
export const ADDRESS_LIST_GET_API_SUCCESS = 'ADDRESS_LIST_GET_API_SUCCESS';
export const ADDRESS_LIST_GET_API_FAILURE = 'ADDRESS_LIST_GET_API_FAILURE';

export const ADDRESS_BY_ID_DELETE_API_REQUEST =
	'ADDRESS_BY_ID_DELETE_API_REQUEST';
export const ADDRESS_BY_ID_DELETE_API_SUCCESS =
	'ADDRESS_BY_ID_DELETE_API_SUCCESS';
export const ADDRESS_BY_ID_DELETE_API_FAILURE =
	'ADDRESS_BY_ID_DELETE_API_FAILURE';

export const ADDRESS_RESPONSE_MESSAGE = 'ADDRESS_RESPONSE_MESSAGE';

export const MAKE_CALENDAR_UNAVAILABLE_DATE_POST_API_REQUEST =
	'MAKE_CALENDAR_UNAVAILABLE_DATE_POST_API_REQUEST';
export const MAKE_CALENDAR_UNAVAILABLE_DATE_POST_API_SUCCESS =
	'MAKE_CALENDAR_UNAVAILABLE_DATE_POST_API_SUCCESS';
export const MAKE_CALENDAR_UNAVAILABLE_DATE_POST_API_FAILURE =
	'MAKE_CALENDAR_UNAVAILABLE_DATE_POST_API_FAILURE';

export const CALENDAR_UNAVAILABLE_DATE_LIST_GET_API_REQUEST =
	'CALENDAR_UNAVAILABLE_DATE_LIST_GET_API_REQUEST';
export const CALENDAR_UNAVAILABLE_DATE_LIST_GET_API_SUCCESS =
	'CALENDAR_UNAVAILABLE_DATE_LIST_GET_API_SUCCESS';
export const CALENDAR_UNAVAILABLE_DATE_LIST_GET_API_FAILURE =
	'CALENDAR_UNAVAILABLE_DATE_LIST_GET_API_FAILURE';

export const RESET_ONLY_CALENDAR_FROM_STORE = 'RESET_ONLY_CALENDAR_FROM_STORE';

// export const PRESENT_HIRE_MAKE_PAYMENT_SCREEN_MODAL =
// 	'PRESENT_HIRE_MAKE_PAYMENT_SCREEN_MODAL';
// export const HIDE_HIRE_MAKE_PAYMENT_SCREEN_MODAL =
// 	'HIDE_HIRE_MAKE_PAYMENT_SCREEN_MODAL';

export const PRESENT_SAVED_CARD_SCREEN_MODAL =
	'PRESENT_SAVED_CARD_SCREEN_MODAL';
export const HIDE_SAVED_CARD_SCREEN_MODAL = 'HIDE_SAVED_CARD_SCREEN_MODAL';

export const HIRE_ITEM_BY_ID_GET_API_REQUEST =
	'HIRE_ITEM_BY_ID_GET_API_REQUEST';
export const HIRE_ITEM_BY_ID_GET_API_SUCCESS =
	'HIRE_ITEM_BY_ID_GET_API_SUCCESS';
export const HIRE_ITEM_BY_ID_GET_API_FAILURE =
	'HIRE_ITEM_BY_ID_GET_API_FAILURE';

export const SHOULD_RUN_FUNCTION = 'SHOULD_RUN_FUNCTION';

export const CALENDAR_HEADER_TITLE = 'CALENDAR_HEADER_TITLE';

export const HIRE_ITEM_POST_API_REQUEST = 'HIRE_ITEM_POST_API_REQUEST';
export const HIRE_ITEM_POST_API_SUCCESS = 'HIRE_ITEM_POST_API_SUCCESS';
export const HIRE_ITEM_POST_API_FAILURE = 'HIRE_ITEM_POST_API_FAILURE';

export const BUY_ITEM_POST_API_REQUEST = 'BUY_ITEM_POST_API_REQUEST';
export const BUY_ITEM_POST_API_SUCCESS = 'BUY_ITEM_POST_API_SUCCESS';
export const BUY_ITEM_POST_API_FAILURE = 'BUY_ITEM_POST_API_FAILURE';

export const HIRE_ITEM_PAYMENT_SUCCESS = 'HIRE_ITEM_PAYMENT_SUCCESS';

export const ACCOUNT_DELETE_API_REQUEST = 'ACCOUNT_DELETE_API_REQUEST';
export const ACCOUNT_DELETE_API_SUCCESS = 'ACCOUNT_DELETE_API_SUCCESS';
export const ACCOUNT_DELETE_API_FAILURE = 'ACCOUNT_DELETE_API_FAILURE';

export const BUSINESS_PROFILE_GET_API_REQUEST =
	'BUSINESS_PROFILE_GET_API_REQUEST';
export const BUSINESS_PROFILE_GET_API_SUCCESS =
	'BUSINESS_PROFILE_GET_API_SUCCESS';
export const BUSINESS_PROFILE_GET_API_FAILURE =
	'BUSINESS_PROFILE_GET_API_FAILURE';

export const BUSINESS_PROFILE_POST_API_REQUEST =
	'BUSINESS_PROFILE_POST_API_REQUEST';
export const BUSINESS_PROFILE_POST_API_SUCCESS =
	'BUSINESS_PROFILE_POST_API_SUCCESS';
export const BUSINESS_PROFILE_POST_API_FAILURE =
	'BUSINESS_PROFILE_POST_API_FAILURE';

export const PAUSE_RESUME_POST_API_REQUEST = 'PAUSE_RESUME_POST_API_REQUEST';
export const PAUSE_RESUME_POST_API_SUCCESS = 'PAUSE_RESUME_POST_API_SUCCESS';
export const PAUSE_RESUME_POST_API_FAILURE = 'PAUSE_RESUME_POST_API_FAILURE';

export const FACEBOOK_REGISTRATION_POST_API_REQUEST =
	'FACEBOOK_REGISTRATION_POST_API_REQUEST';
export const FACEBOOK_REGISTRATION_POST_API_SUCCESS =
	'FACEBOOK_REGISTRATION_POST_API_SUCCESS';
export const FACEBOOK_REGISTRATION_POST_API_FAILURE =
	'FACEBOOK_REGISTRATION_POST_API_FAILURE';

export const APPLE_REGISTRATION_POST_API_REQUEST =
	'APPLE_REGISTRATION_POST_API_REQUEST';
export const APPLE_REGISTRATION_POST_API_SUCCESS =
	'APPLE_REGISTRATION_POST_API_SUCCESS';
export const APPLE_REGISTRATION_POST_API_FAILURE =
	'APPLE_REGISTRATION_POST_API_FAILURE';

export const CLEAR_HIRE_CALCULATED_DISTANCE = 'CLEAR_HIRE_CALCULATED_DISTANCE';
export const CLEAR_COLLECTIONTYPE_PICKER_DEFAULT_VALUE =
	'CLEAR_COLLECTIONTYPE_PICKER_DEFAULT_VALUE';

export const FIND_DISTANCE_GET_API_REQUEST = 'FIND_DISTANCE_GET_API_REQUEST';
export const FIND_DISTANCE_GET_API_SUCCESS = 'FIND_DISTANCE_GET_API_SUCCESS';
export const FIND_DISTANCE_GET_API_FAILURE = 'FIND_DISTANCE_GET_API_FAILURE';

export const HIRING_LIST_GET_API_REQUEST = 'HIRING_LIST_GET_API_REQUEST';
export const HIRING_LIST_GET_API_SUCCESS = 'HIRING_LIST_GET_API_SUCCESS';
export const HIRING_LIST_GET_API_FAILURE = 'HIRING_LIST_GET_API_FAILURE';

export const HIRING_OUT_LIST_GET_API_REQUEST =
	'HIRING_OUT_LIST_GET_API_REQUEST';
export const HIRING_OUT_LIST_GET_API_SUCCESS =
	'HIRING_OUT_LIST_GET_API_SUCCESS';
export const HIRING_OUT_LIST_GET_API_FAILURE =
	'HIRING_OUT_LIST_GET_API_FAILURE';

export const FORGOT_PASSWORD_POST_API_REQUEST =
	'FORGOT_PASSWORD_POST_API_REQUEST';
export const FORGOT_PASSWORD_POST_API_SUCCESS =
	'FORGOT_PASSWORD_POST_API_SUCCESS';
export const FORGOT_PASSWORD_POST_API_FAILURE =
	'FORGOT_PASSWORD_POST_API_FAILURE';

export const HIRING_BY_ID_GET_API_REQUEST = 'HIRING_BY_ID_GET_API_REQUEST';
export const HIRING_BY_ID_GET_API_SUCCESS = 'HIRING_BY_ID_GET_API_SUCCESS';
export const HIRING_BY_ID_GET_API_FAILURE = 'HIRING_BY_ID_GET_API_FAILURE';

export const PRESENT_HIRE_FILTER_SCREEN_MODAL =
	'PRESENT_HIRE_FILTER_SCREEN_MODAL';
export const HIDE_HIRE_FILTER_SCREEN_MODAL = 'HIDE_HIRE_FILTER_SCREEN_MODAL';

export const CALENDAR_DATE_BY_ID_DELETE_API_REQUEST =
	'CALENDAR_DATE_BY_ID_DELETE_API_REQUEST';
export const CALENDAR_DATE_BY_ID_DELETE_API_SUCCESS =
	'CALENDAR_DATE_BY_ID_DELETE_API_SUCCESS';
export const CALENDAR_DATE_BY_ID_DELETE_API_FAILURE =
	'CALENDAR_DATE_BY_ID_DELETE_API_FAILURE';

export const PRESENT_DETAIL_FINANCE_SCREEN_MODAL =
	'PRESENT_DETAIL_FINANCE_SCREEN_MODAL';
export const HIDE_DETAIL_FINANCE_SCREEN_MODAL =
	'HIDE_DETAIL_FINANCE_SCREEN_MODAL';

export const POST_ADVERT_FROM_SEARCH_LANDING_SCREEN =
	'POST_ADVERT_FROM_SEARCH_LANDING_SCREEN';

export const STRIPE_CONNECT_GET_API_REQUEST = 'STRIPE_CONNECT_GET_API_REQUEST';
export const STRIPE_CONNECT_GET_API_SUCCESS = 'STRIPE_CONNECT_GET_API_SUCCESS';
export const STRIPE_CONNECT_GET_API_FAILURE = 'STRIPE_CONNECT_GET_API_FAILURE';

export const ADD_CARD_WEBVIEW_GET_API_REQUEST =
	'ADD_CARD_WEBVIEW_GET_API_REQUEST';
export const ADD_CARD_WEBVIEW_GET_API_SUCCESS =
	'ADD_CARD_WEBVIEW_GET_API_SUCCESS';
export const ADD_CARD_WEBVIEW_GET_API_FAILURE =
	'ADD_CARD_WEBVIEW_GET_API_FAILURE';

export const CLEAR_ADD_CARD_HTML = 'CLEAR_ADD_CARD_HTML';

export const LIST_USER_CARD_GET_API_REQUEST = 'LIST_USER_CARD_GET_API_REQUEST';
export const LIST_USER_CARD_GET_API_SUCCESS = 'LIST_USER_CARD_GET_API_SUCCESS';
export const LIST_USER_CARD_GET_API_FAILURE = 'LIST_USER_CARD_GET_API_FAILURE';

export const DEFAULT_CARD_POST_API_REQUEST = 'DEFAULT_CARD_POST_API_REQUEST';
export const DEFAULT_CARD_POST_API_SUCCESS = 'DEFAULT_CARD_POST_API_SUCCESS';
export const DEFAULT_CARD_POST_API_FAILURE = 'DEFAULT_CARD_POST_API_FAILURE';

export const CARD_DELETE_DEFAULT_SUCCESS = 'CARD_DELETE_DEFAULT_SUCCESS';

export const CARD_DELETE_API_REQUEST = 'CARD_DELETE_API_REQUEST';
export const CARD_DELETE_API_SUCCESS = 'CARD_DELETE_API_SUCCESS';
export const CARD_DELETE_API_FAILURE = 'CARD_DELETE_API_FAILURE';

export const HIRE_ITEM_PAYMENT_POST_API_REQUEST =
	'HIRE_ITEM_PAYMENT_POST_API_REQUEST';
export const HIRE_ITEM_PAYMENT_POST_API_SUCCESS =
	'HIRE_ITEM_PAYMENT_POST_API_SUCCESS';
export const HIRE_ITEM_PAYMENT_POST_API_FAILURE =
	'HIRE_ITEM_PAYMENT_POST_API_FAILURE';

export const HIRE_ITEM_STRIPE_PAYMENT_SUCCESS =
	'HIRE_ITEM_STRIPE_PAYMENT_SUCCESS';

export const BUY_ITEM_PAYMENT_POST_API_REQUEST =
	'BUY_ITEM_PAYMENT_POST_API_REQUEST';
export const BUY_ITEM_PAYMENT_POST_API_SUCCESS =
	'BUY_ITEM_PAYMENT_POST_API_SUCCESS';
export const BUY_ITEM_PAYMENT_POST_API_FAILURE =
	'BUY_ITEM_PAYMENT_POST_API_FAILURE';

export const BUY_ITEM_PAYMENT_SUCCESS = 'BUY_ITEM_PAYMENT_SUCCESS';

export const SEND_EMAIL_POST_API_REQUEST = 'SEND_EMAIL_POST_API_REQUEST';
export const SEND_EMAIL_POST_API_SUCCESS = 'SEND_EMAIL_POST_API_SUCCESS';
export const SEND_EMAIL_POST_API_FAILURE = 'SEND_EMAIL_POST_API_FAILURE';

export const CANCEL_HIRING_POST_API_REQUEST = 'CANCEL_HIRING_POST_API_REQUEST';
export const CANCEL_HIRING_POST_API_SUCCESS = 'CANCEL_HIRING_POST_API_SUCCESS';
export const CANCEL_HIRING_POST_API_FAILURE = 'CANCEL_HIRING_POST_API_FAILURE';

export const NEAR_ME_HIRE_POST_API_REQUEST = 'NEAR_ME_HIRE_POST_API_REQUEST';
export const NEAR_ME_HIRE_POST_API_SUCCESS = 'NEAR_ME_HIRE_POST_API_SUCCESS';
export const NEAR_ME_HIRE_POST_API_FAILURE = 'NEAR_ME_HIRE_POST_API_FAILURE';

export const NEAR_ME_BUY_POST_API_REQUEST = 'NEAR_ME_BUY_POST_API_REQUEST';
export const NEAR_ME_BUY_POST_API_SUCCESS = 'NEAR_ME_BUY_POST_API_SUCCESS';
export const NEAR_ME_BUY_POST_API_FAILURE = 'NEAR_ME_BUY_POST_API_FAILURE';

export const PRESENT_STRIPE_REVIEW_DETAIL_SCREEN_MODAL =
	'PRESENT_STRIPE_REVIEW_DETAIL_SCREEN_MODAL';
export const HIDE_STRIPE_REVIEW_DETAIL_SCREEN_MODAL =
	'HIDE_STRIPE_REVIEW_DETAIL_SCREEN_MODAL';

export const STRIPE_BALANCE_GET_API_REQUEST = 'STRIPE_BALANCE_GET_API_REQUEST';
export const STRIPE_BALANCE_GET_API_SUCCESS = 'STRIPE_BALANCE_GET_API_SUCCESS';
export const STRIPE_BALANCE_GET_API_FAILURE = 'STRIPE_BALANCE_GET_API_FAILURE';

export const DAY_TO_PRICE_POST_API_REQUEST = 'DAY_TO_PRICE_POST_API_REQUEST';
export const DAY_TO_PRICE_POST_API_SUCCESS = 'DAY_TO_PRICE_POST_API_SUCCESS';
export const DAY_TO_PRICE_POST_API_FAILURE = 'DAY_TO_PRICE_POST_API_FAILURE';

// export const FORCE_UPDATE_GET_API_REQUEST = 'FORCE_UPDATE_GET_API_REQUEST';
// export const FORCE_UPDATE_GET_API_SUCCESS = 'FORCE_UPDATE_GET_API_SUCCESS';
// export const FORCE_UPDATE_GET_API_FAILURE = 'FORCE_UPDATE_GET_API_FAILURE';
